name: aly_oss_example
description: Demonstrates how to use the aly_oss plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.6.1+11

dev_dependencies:
  flutter_test:
    sdk: flutter

  aly_oss:
    path: ../

flutter:

#  assets:
#    - assets/tower.jpg
